services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      DISK_SIZE: "64G"
      RAM_SIZE: "6G"
      CPU_CORES: "6"
      USERNAME: "root"
      PASSWORD: "root"
      REGION: "ko-KR"
      DHCP: "N"
      KVM: "N"
    devices:
      # 해당 운영체제가 KVM을 지원 해야함
      # - /dev/kvm
      # TUN 디바이스 설정 여부
      - /dev/net/tun
    cap_add:
    # 네트워크 생성 및 설정 권한 부여
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
    # 프로젝트 파일 내에 example.iso 파일이 존재해야함
      - ./example.iso:/example.iso
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
networks:
  default:
    driver: bridge

